### ISSUE TITLE
Don't cache the admin UI queries?

### ISSUE THREAD

**Issue by lee-kagiso** [BertrandBordage/django-cachalot#30]
We are noticing that our cache is 3 times the size of our database, and as it is on Heroku it is getting very expensive. 

Could this be due to caching admin UI queries? We only want to cache the user facing parts of our site (news articles/typical CMS stuff), and something is amiss...

**Comment by BertrandBordage** [comment]
3 times the database size is normal. If you want a smaller cache, simply change the cache size limit. I don’t know if you can do that on Heroku (never used it), but you can definitely do it with Redis, memcached, locmem and filebased.

This can be due to admin queries, it totally depends on how you and your readers use the website. If you don’t want the admin to use the cache, you can write a middleware that disables django-cachalot if the app of the current view is 'admin'. It should take less 5-10 lines.
