### ISSUE TITLE
Support for django_pylibmc (Heroku)?

### ISSUE THREAD

**Issue by lakshbhasin** [BertrandBordage/django-cachalot#42]
Hi there. I was looking to use django-cachalot with a Django site I've deployed on Heroku. I'm using the third-party [django_pylibmc](https://github.com/django-pylibmc/django-pylibmc) package to make use of Heroku's Memcached addon, because Django's default pylibmc (i.e. `django.core.cache.backends.memcached.PyLibMCCache`) does not support the binary protocol (see [this StackOverflow post](http://stackoverflow.com/questions/17663169/configuring-django-cache-machine-on-heroku-memcachier) and [this DjangoProject ticket](https://code.djangoproject.com/ticket/15815)). With the django_pylibmc package, I am able to get my Heroku site working with Memcachier.

Unfortunately, django_pylibmc does not work with django-cachalot. When I run `heroku run python manage.py migrate`, I get the following error message:

```
(cachalot.E001) `django_pylibmc.memcached.PyLibMCCache` is not compatible with django-cachalot.
```

Are there any plans for supporting django_pylibmc? I'd really love it if I could use django-cachalot on my Heroku site, since it seems to be a very robust and useful package.

**Comment by BertrandBordage** [comment]
Hello @lakshbhasin!

There is no plan for supporting django-pylibmc. I understand that the binary protocol may be useful to some users. But adding a supported backend would add 33 test runs to the [test matrix](https://travis-ci.org/BertrandBordage/django-cachalot) that already contains 165 test runs and takes about an hour to run. Since django-pylibmc is a tiny addition (a few dozens of lines) from the Django pylibmc backend, it’s not worth it. I see django-pylibmc as a patch to [django/django#15815](https://code.djangoproject.com/ticket/15815). It just needs to be pushed upstream to Django by someone.

In the meantime, I tested locally and everything works. So you can still ignore the error by using [`SILENCED_SYSTEM_CHECKS`](https://docs.djangoproject.com/en/1.9/ref/settings/#silenced-system-checks). It won’t be officially supported, but it works with django-cachalot 1.1.0 and will work with django-cachalot 1.2.0 (that will be released today or in a few days).

**Comment by orf** [comment]
As a side note an hour to run the test suite is excessive, it sounds like
there is considerable room for improvement. Have you tried parallelizing
the tests?

**Comment by BertrandBordage** [comment]
@orf It’s not a single test suite that takes one hour, it’s the whole test matrix that tests django-cachalot against:
- Python 2.7, 3.2, 3.3, 3.4, 3.5
- Django 1.7, 1.8, 1.9
- PostgreSQL, MySQL, SQLite
- Redis, python-memcached, pylibmc, locmem, filebased

It therefore runs the test suite 165 times. Each test suite takes about 1 minute 30 seconds, and Travis CI runs 3 test suites in parallel, so we end up with about an hour of execution.
In django 1.9, the tests are run in parallel, but it has nearly no effect on the test suite of django-cachalot, since most of the time on Travis consists in building the environment.

**Comment by JockeTF** [comment]
You may want to clear out versions that have reached end-of-life, [such as Django 1.7](https://www.djangoproject.com/download/).

**Comment by BertrandBordage** [comment]
@JockeTF: Yes, that’s what I wanted to do for version 1.2.0, but supporting Django 1.7 currently doesn’t require any compatibility code, so I’m in favor of supporting it yet a few months.

**Comment by imposeren** [comment]
> SILENCED_SYSTEM_CHECKS only works for WARNINGS. So there is now effective way of ignoring errors except for monkeypatching ``cachalot.apps.VALID_CACHE_BACKENDS``. This also disalbes use of even slightly modified cache backends. Maybe VALID_CACHE_BACKENDS should be configurable through settings?

**Comment by BertrandBordage** [comment]
@imposeren No, it works for all checks, including `ERROR`. Try or read the docs.
