### ISSUE TITLE
tiny documentation error

### ISSUE THREAD

**Issue by MattBroach** [BertrandBordage/django-cachalot#48]
Only just because I literally **just** had to deal with this issue on my server, I thought I'd point out: in the part of your documentation about memcached size limit issues, the limit per cache key command actually requires a unit.  Setting the max cache size to 10MB would be `-I 10m`, not `-I 10`.  It's weirdly inconsistent, because the units are **not** used with the overall max memory (the `-m 1000` to set the overall max it 1GB is correct), but there you have it.

This seemed like too minor a thing to make a PR over, but I wanted to give you a heads up.  Otherwise, thanks for the great work.

**Comment by BertrandBordage** [comment]
Thank you @MattBroach for spotting this!
Yes, this is completely inconsistent as we can see on [the man page](http://linux.die.net/man/1/memcached), `-m` is waiting for a number of MB while `-I` is waiting for a size, therefore containing SI prefixes…

Fixed with d2c9274d5d9b4e3714129858a8d606089c04ef18.
