### ISSUE TITLE
Profiling Django-Cachalot

### ISSUE THREAD

**Issue by boxbeatsy** [BertrandBordage/django-cachalot#54]
I've just implemented Django-Cachalot for my Heroku production app, and everything has been running very smoothly.  Thank you for the great work!

I recently took a look at our memcached metrics and noticed that the datastore size has been steadily growing since we launched the package (currently at 20GB, 3.5x the size our actual Postgres DB, with no signs of slowing down).

Given the cost of running a memcached server, we need a way to profile our app under Django-cachalot to determine whether the cost of keeping this data in cache is worth the gains in query speed.

We decided the important profiling metrics for our application were:
- Total # of Cache Hits (both in aggregate and by model)
- Total # of Cache Misses (both in aggregate and by model)
- Average storage size of cached objects (both in aggregate and by model)

Here is the first draft of our monkey patch of Django-Cachalot that we'll be temporarily deploying to profile the current cache's effectiveness: https://gist.github.com/boxbeatsy/87bdbc8f997872c77856c4d8cc8638f4

Here is a reporting script: https://gist.github.com/boxbeatsy/fda5cfe1eb5af03d5289b63f0bd339fd

Does anyone have additional guidance on how to better profile our app?  Would this be something  worth adding to Django-Cachalot? (I imagine profiling would be an important operational question for anyone deploying this in production at scale).

**Comment by boxbeatsy** [comment]
After a little more digging, I've found that invalidating tables doesn't actually delete any keys from  cache.  It waits for LRU to evict old keys, which is most efficient (no use deleting keys in practice).  However, it does make it really hard to determine how much space Django-Cachalot requires in production to operate at maximum efficiency.  What about adding a management function that deletes all expired cachalot keys?  This would be very inefficient, but could be used sparingly to understand how much  space cachalot is actually using.

**Comment by BertrandBordage** [comment]
First of all, you should set the memcached memory limit. Once it’s set, there’s no surprise: it will not take more than what you allow. And therefore no need for profiling.

Now, it would indeed be great to have better tools for profiling caches. Unfortunately, caches absolutely don’t work like a database, and that’s the cost for being as fast as possible. The only reliable thing with a cache is: asking for what’s stored at a certain key, and set the value for a certain key. Forget what you think you know about timeouts etc: none of it is reliable. If you create a key with an infinite timeout, it can very well be removed before a key with a 1 second timeout (if you want to know more about it, read [this article in the Redis docs](http://redis.io/topics/lru-cache)).

I’m sorry, but there’s no viable solution to make a command that deletes expired cachalot keys. I know it could be possible using Redis (or using other caches with non-standard hacks), but that would take hours on a big cache…

However, because tons of people requested it, **I will add a way to specify cachalot’s timeout** in the upcoming major release… For me, there is no good reason to use it, configuring properly the cache backend is the solution, not using a timeout that doesn’t work as 99.5% people think it does. But if users feel at home by having it…
