### ISSUE TITLE
DiskCache compatibility

### ISSUE THREAD

**Issue by mheppner** [BertrandBordage/django-cachalot#57]
Are there any plans to support [DiskCache](https://github.com/grantjenks/python-diskcache)? I haven't tried it yet. The docs don't seem to mention if 3rd party caches are supported or what it would take implement.

Also, the docs mention going to the Google Groups page to ask questions, but I applied for membership over a week ago and it doesn't look like I have access. Are you open to switching to Gitter or Slack?

**Comment by BertrandBordage** [comment]
No plan for DiskCache support. I don’t understand what’s really interesting about it: it’s a bit faster than many caches for reading, but it’s terribly slow for writing. Even filebased is a better compromise, and it’s only a few dozen lines of code.

About Google Groups, that’s weird, I didn’t receive your notification :\ You’re right, Google Groups is starting to be annoying with these mandatory membership system…

I just created a Slack team on [django-cachalot.slack.com](django-cachalot.slack.com), it will be way easier.

**Comment by mheppner** [comment]
Completely makes sense. I posted this before I tried it in a local environment and you're right, it's extremely slow for writes. If you adjust the shards to 1 then it gives decent write speeds.

Thanks for creating the Slack channel, I'll join it :)  Also, great work on this project, it should exist in Django core!

**Comment by BertrandBordage** [comment]
Thanks! Well, it could be in Django core, but the best solution would be to create a PostgreSQL query cache (and maybe a SQLite query cache) like the one in MySQL. It would be simpler and would work on any project, not only Django projects :)

One day, I may do it… I tried to do it at the PostgreSQL Python binding level by creating a new pure Python PostgreSQL binding. It ended up being way faster than psycopg2 (even with django-cachalot), but I gave up for the moment because I had no funding for it and already spent too much spare time on it.

**Comment by mheppner** [comment]
I think it would still have value to have it in Django core, simply because it's database agnostic. A lot of people using shared hosting may not even be able to adjust their MySQL settings to turn on the query cache. I don't know too much about the internals of Django querysets, or even what your monkeypatch is doing, but let me know if I can help out somehow!
