### ISSUE TITLE
Django-CMS,sqlite, cachalot, memcached , apache, - site lock

### ISSUE THREAD

**Issue by Troyhy** [BertrandBordage/django-cachalot#6]
We experienced weird hangups of our test site with configuration mentioned in title.
There was 2 users making edits in Django-CMS  and 4 times we had to restart application because it was locked.
Site started to serve content, but never returned anything, until restart of wsgi process. Apache was happily serving other django sites. With only one person editing there were no problems.
This locking occurred only after configuring cachalot.

Sorry I cannot be more specific on  this issue.

**Comment by BertrandBordage** [comment]
Thanks for reporting!

django-cachalot currently skips tests for concurrent updates with SQLite. I thought this wasn’t necessary since [you must expect locks in this case](https://docs.djangoproject.com/en/1.7/ref/databases/#database-is-locked-errors).

But it clearly breaks an expected behaviour, so I’ll fix this issue before version 1.0 and add tests.
It either comes from the atomicity system or an unclosed connection.

Can you [increase SQLite timeout](https://docs.djangoproject.com/en/1.7/ref/databases/#database-is-locked-errors) to see if the same issue occur? That could be a temporary workaround for you.

**Comment by BertrandBordage** [comment]
Could you please specify your versions of django-cachalot, Django & Python?

**Comment by BertrandBordage** [comment]
I tried to reproduce using Python 2.7, Django 1.7, django-cms 3.0.7, django-cachalot 0.9.0, memcached and gunicorn (it’s also a wsgi server), but failed.
All I can get is `OperationalError: database is locked` when modifying two pages exactly at the same time. (That’s the expected behaviour.) But everything work flawlessly after.

So you’ll have to help me on this. Can you at least privately mail me your `settings.py` (stripped from all passwords)?

**Comment by Troyhy** [comment]
Sorry about delay.. here is some more info
Django==1.6.9
django-cms==3.0.7
django-cachalot==0.9.0
django-debug-toolbar==1.2.2
django-extensions==1.4.9
django-mptt==0.6.1
django-sekizai==0.8.1
python-memcached==1.53


Apache (in debian wheezy platform)
apache2 2.2.16
libapache2-mod-wsgi 3.3.2

Python 2.6.6

settings is coming via mail...

**Comment by BertrandBordage** [comment]
@Troyhy Do you have more info on this? Our mail discussion wasn’t really conclusive.

**Comment by szymek116** [comment]
as mentioned earlier check this project, still not prod version but works
for me and even has better hit rate than JC:

https://github.com/BertrandBordage/django-cachalot


2015-02-22 6:05 GMT+01:00 Bertrand Bordage <notifications@github.com>:

**Comment by BertrandBordage** [comment]
Reopen if it’s still relevant.
