### ISSUE TITLE
Settings for (UN)CACHABLE_TABLES use SQL table names instead of app+model names?

### ISSUE THREAD

**Issue by Bartvds** [BertrandBordage/django-cachalot#69]
According to the docs the CACHABLE_TABLES and UNCACHABLE_TABLES settings need to be specified as the SQL table names, instead of a dotted appname.modelname (like cacheops). 

I think this is not really the Django way to do this, as it bypasses the abstraction Django puts over the database. So instead of working at the Django level (models) I now have to inspect the database and figure-out what Django does to turn model names into table names. It is not a huge deal but not something we should have to do when using an abstraction like Django.

**Comment by BertrandBordage** [comment]
I agree this would be nice.

However there are three reasons why I chose to only support table names in these settings:
- Performance: if we allowed model accessors, we would have to convert them to table names all the time. Because django-cachalot supports dynamic settings changes, the only solution would be to modify `CACHABLE_TABLES` and `UNCACHABLE_TABLES` each time they are changed, so that their accessors are converted to table names. This would be a nice solution, but unfortunately it’s not possible with Django. The closest we have to do this is the [`settings_changed`](https://docs.djangoproject.com/en/1.10/ref/signals/#setting-changed) signal, but it’s not always triggered, as stated in the docs.
- Possibilities: it happens to have tables (or even database views) defined outside the Django ORM but used in your Django project. Even the Django ORM defines models not accessible from the accessors `app.Model`: the many-to-many models and the `Migration` model. (Yes, these models really exist.)
- Difficulty: a django-cachalot user that needs to change `CACHABLE_TABLES` or `UNCACHABLE_TABLES` obviously knows how to find a table name.

I close this issue with a “won’t fix” label for now, but as soon as a solution is possible, I’ll implement it.
