### ISSUE TITLE
default redis maxmemory-policy considered harmful

### ISSUE THREAD

**Issue by stefantalpalaru** [BertrandBordage/django-cachalot#7]
Please specify somewhere in the documentation that if redis is used as the caching backend, its "maxmemory-policy" settings should be changed to "allkeys-lru" otherwise you risk OOM exceptions bringing the site down.

(the default "volatile-lru" will not remove the keys set by cachalot without an expiry interval)

**Comment by BertrandBordage** [comment]
It’s not harmful, on the contrary, it’s a safety. Otherwise one could lose important data since Redis is also used as a database.

We can’t recommend to set `maxmemory-policy` to `allkeys-lru` since it may not be what one would expect from Redis.  Django-cachalot will probably not be the only application using Redis on most servers, so it could lead to data loss on another application because the configuration is the same for all its 'databases'.

In my case, the solution was to increase `maxmemory`. The number of possible SQL queries tends to be limited on most projects if they are not too combinatorial.  Since the same cache keys are used after an invalidation, this means that a high `maxmemory` like `16GB` is enough for a large project.  It’s been 5 months since I set this on two major projects, and no OOM exception occurred.

But I agree that this situation may be perplexing for someone who installed Redis and expects a memcached-like service.  Even though it’s a Redis 'issue', I’m in favor of mentioning it in the docs and adding a link to [this Redis page](http://redis.io/topics/lru-cache) while summarizing that one probably wants to use more memory or `allkeys-lru`.

Can you make a pull request? :)

**Comment by stefantalpalaru** [comment]
It brought down a site while I was sleeping, so yeah, it's harmful ;-)

Maybe cachalot should catch that OOM exception instead of letting it compromise the whole request?

**Comment by BertrandBordage** [comment]
Catching the exception will not solve this, it’ll make it worse it most cases.

Most people will have Redis as their default Django cache backend, so Redis will not be used only by cachalot. So while cachalot may be able to silence this issue, another part of a view may raise the same exception, for example if template fragment caching is used.

So if we catch the exception, a developer will wonder why the exception occurred in template fragment caching and not in cachalot.

The only way to solve this is by warning the users that **Redis is not a LRU cache by default**. It could even be in the django-redis documentation.  A good place for this warning in the django-cachalot docs is in “Limits”, don’t you think?

**Comment by stefantalpalaru** [comment]
You're right about exception catching. Another way you may avoid this in cachalot is to set a (very long) expiry for your keys.

Yes, 'Limits' is a good section for that piece of info. I wouldn't say that Redis is not a LRU cache by default, just that its default eviction policy ignores persistent keys.

**Comment by BertrandBordage** [comment]
Yes, setting a very long expiry could also be a solution, but that’s less clean. Another downside is that setting an expiry slows down `cache.set` and even `cache.get` of a few μs.  Maybe it slows down eviction too, I’m not sure.  2-5 μs isn’t much, but since we try to be as fast as possible… :p

Do you want to write that section?

**Comment by stefantalpalaru** [comment]
pull request created

**Comment by BertrandBordage** [comment]
Fixed by #9.
Thanks @stefantalpalaru!
