### ISSUE TITLE
Don't cache any queries that use RawSQL

### ISSUE THREAD

**Issue by schinckel** [BertrandBordage/django-cachalot#70]
Because of the nature of a ``RawSQL`` query, that may refer to any other tables, cachalot should not cache any queries that contain a ``RawSQL`` clause.

**Comment by BertrandBordage** [comment]
Raw queries are not cached. Did you find a case where raw queries are cached?

**Comment by schinckel** [comment]
When you use `.annotate(field_name=RawSQL())`, it caches the query.

**Comment by BertrandBordage** [comment]
You’re right, I forgot this feature was introduced in Django 1.8, sorry :\
I’ll write tests for it, then detect table names in it to invalidate such queries, like I do for the other raw queries (see http://django-cachalot.readthedocs.io/en/latest/limits.html#raw-sql-queries).

**Comment by schinckel** [comment]
No worries.

In our case, it's not the `RawSQL()` containing altering statements, but more that it references other tables (usually by a subquery), and when those tables are altered, the query containing the `RawSQL` then needs to be invalidated.

I think that's what you meant by your comment above, but the link referred to UPDATE and other statements.

**Comment by BertrandBordage** [comment]
Yes, there is [an additional feature](https://github.com/BertrandBordage/django-cachalot/blob/master/cachalot/utils.py#L165-L169) not mentioned in the docs, table names are detected even when there is no `UPDATE` etc, and they are added to the list of tables to check to see if the query is still valid.

**Comment by BertrandBordage** [comment]
In fact, after an afternoon of digging, it turns out `RawSQL` was correctly handled by django-cachalot, though it was not tested.

`RawSQL` is considered as a raw subquery by Django (like some other query types like `HAVING`, generated using `QuerySet`s such as `User.objects.annotate(n=Count('user_permissions')).filter(n__gte=1)`), and when django-cachalot detects a raw subquery, it converts it to SQL in order to find table names inside it.

So `RawSQL` already worked: it was cached and correctly invalidated, and it’s still the case. I added a test to be extra sure.
