### ISSUE TITLE
Cache growth from queries with incrementing date/time/etc on infrequent invalidated tables

### ISSUE THREAD

**Issue by Bartvds** [BertrandBordage/django-cachalot#71]
Not sure if this a problem, but we spotted an interesting situation when querying on date/datetimes:

If we query with `my_queryset.filter(my_date__lt=timezone.now())` I see in django-debug-toolbar that the value of a datetime is extremely detailed, so we get a ton of cached queries for all the microseconds (as expected). To improve caching we can round the date/time query to nearest X minutes/hours/days so we get more cache hits. 

But combined with the lack of TTL on cached values (according to docs at least in redis) *and* a table that doesn't invalidate often we get a giant pileup of old cached queries. We can work around this by not caching these tables, disabling the cache on per-query basis, or periodically flushing them.

What do you think? I'm still a bit unclear why the redis cache doesn't have a TTL at all? How does this situation work with memcached?

We use mixed persistent and ttl keys in redis using `volatile-lru` with other redis based apps and it works fine. Cachalot doesn't seem to mind if I randomly delete keys (docs even suggest `allkeys-lru`), so then why no TTL at all (not even optional?)

**Comment by BertrandBordage** [comment]
If you really want to use a timeout, you can use [`CACHALOT_TIMEOUT`](http://django-cachalot.readthedocs.io/en/latest/quickstart.html#cachalot-timeout) since django-cachalot 1.3.0.

But be aware that persistent cache keys are not **that** persistent. LRU implementations are not always perfect (read [this Redis docs page](http://redis.io/topics/lru-cache)), so it’s better in my opinion to use `allkeys-lru` in Redis if you only use it as a cache.

For your particular case, I would recommend using [`Now()`](https://docs.djangoproject.com/en/1.10/ref/models/database-functions/#now) (or `TransactionNow`). When you use this, django-cachalot will never cache the query.
