### ISSUE TITLE
Is it possible to use cachalot only for specific apps?

### ISSUE THREAD

**Issue by fabiocaccamo** [BertrandBordage/django-cachalot#75]
It would be very useful, especially for third parties apps that would use cachalot in existing projects where a caching layer is already present.

**Comment by BertrandBordage** [comment]
I’m not sure that would be very useful. The idea of django-cachalot is to make every query run faster, so why would you want to disable it in some parts? To gain a little memory? I don’t think that’s very relevant, because you can configure your cache size limit if you have memory issues.

That being said, you can create a middleware to do that. In a middleware, you have access to `request`, so you can have access to the app name using `request.resolver_match.app_name`. From that point, you can temporarily disable django-cachalot.

Something like:
```python
from django.test.utils import override_settings

def cachalot_exclude_apps(get_response):
    def middleware(request):
        if request.resolver_match.app_name not in ('admin', 'something'):
            with override_settings(CACHALOT_ENABLED=False):
                return get_response(request)
        return get_response(request)

    return middleware
```

Here it would disable django-cachalot on all apps except `admin` and `something`.
