### ISSUE TITLE
Disable during manage.py shell session

### ISSUE THREAD

**Issue by kevinmickey** [BertrandBordage/django-cachalot#78]
Is there a way to disable cachalot during a `manage.py shell` session?

I suppose this might work:
```
settings.CACHALOT_ENABLED = False
....
settings.CACHALOT_ENABLED = True
```

Is there a way to have this happen automatically?  Thanks!

**Comment by BertrandBordage** [comment]
This is possible, but hacky.

Probably the less hacky solution would be to define our own shell command inheriting the original and superseding it in the command line interface, so `shell` would be listed under `cachalot` when we list available commands. However, that’s far from ideal: if we have multiple apps replacing the original `shell` command, then you will only have the features of a single one of them. So we could create a command with a different name than `shell`, but users will not have the reflex to use it, especially because they won’t notice a difference with the original `shell`. `shell_plus` from django-extensions adds a lot of imports, since it’s a noticeable improvement, people use it. By the way, if we disable django-cachalot in `shell`, we have to do it for `shell_plus` and potentially other shells for consistency.

So the temporary answer is: we’re not going to do that.

If Django adds an official way to do that, like a signal or something, then we might create a setting to be able to turn django-cachalot off. Or not, because you could also add this signal in your project in roughly 5 lines of code.
