### ISSUE TITLE
Forbid django_session by default?

### ISSUE THREAD

**Issue by m9psy** [BertrandBordage/django-cachalot#82]
User session checks are performed with similar requests (Django 1.8):
<code>SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'blah-blah-blah-key' AND `django_session`.`expire_date` > '2017-06-20 02:03:19.382000')</code>

The main problem here is `expire_date` parameter, forcing to cache every such request, only with `date` difference. Such requests are being performed every visit and may cause unwanted "cache pollution". Of course it is easily cured by using something like `CACHALOT_UNCACHABLE_TABLES = frozenset(('django_migrations', 'django_session'))` in settings.

**Comment by BertrandBordage** [comment]
The problem is that sessions can be used in other contexts than Django’s middleware.
If you’re really concerned about performance regarding sessions, [use cached session](https://docs.djangoproject.com/en/1.11/topics/http/sessions/#using-cached-sessions). I use `cached_db` in all my projects, I suggest you do the same.
