### ISSUE TITLE
Providing a way to disable caching for data imports

### ISSUE THREAD

**Issue by jayden-emergence** [BertrandBordage/django-cachalot#83]
I've got code for this written but have a couple questions regarding the creation of tests which is the last thing I need before I do a pull request.

Firstly there are 2 ways to use the new feature along with these 2 optional abilities:
1.  You can customize the cache_alias and db_alias to use when invalidating
2.  You can choose not to invalidate the cache when done.

Example 1:
```python
from cachalot.monkey_patch import DISABLE_CACHING

with DISABLE_CACHING:
    DISABLE_CACHING.do_not_invalidate()  # Optional Line, will not invalidate after the with

    # Optional line that allows you to change the cache and db aliases used when invalidating.
    DISABLE_CACHING.set_aliases(cache_alias='default', db_alias='default')

    # Code to run while the cache is disabled
```

Example 2:
```python
from cachalot.monkey_patch import DISABLE_CACHING

try:
    DISABLE_CACHING.enable()

    # Code to run while the cache is disabled

finally:
    # invalidate_cache is only needed if you do not want to invalidate the cache.
    # Also allow you to change the cache and db aliases used when invalidating.
    DISABLE_CACHING.disable(invalidate_cache=False, cache_alias='default', db_alias='default'):
```

Questions:
----
I'm going to start with a copy of read.py.

Should I keep each test like `test_empty` and expand it to include testing before caching is disabled, then with it, then after, and also test with invalidating after and not?

Or should I create tests that actually test each situation like test reading then disabling caching using "with" then test that things are invalidated successfully after using some more selects.  Test selecting then disabling caching using "with" but not invalidating after, do another select and then test that it doesn't invalidate with a select after that.  Tests that actually test disabling caching.  The types of sql queries shouldn't affect whether disabling works or not because I have my code in front of the caching code.

**Comment by BertrandBordage** [comment]
Before going any further, I have to ask you if you managed to make this feature thread-safe.
Because as you maybe know, changing Django settings during runtime is not thread-safe, and therefore is not encouraged as it creates bugs.

As you may have noticed, I removed in 1.5.0 the ability to dynamically override settings because it could end up badly.

**Comment by jayden-emergence** [comment]
I actually use the threads id to specify which thread should be disabled.  I've tested with a local django and tested printing things while hitting it with different threads and only the thread I've told it to be disabled on was actually disabled.  The other threads used the cache until the thread where I disabled it finished and it invalidates the cache.

The class that does all the disabling (with a doc string regarding usage) is here:
https://github.com/emergence/django-cachalot/blob/master/cachalot/monkey_patch.py#L26

I've also written some tests written already.  Instead of using all the tests in read and customizing them all to use the disabled stuff I've got my own module with tests that run thorough each type of disabling that occurs (reading, writing, and raw).

I haven't run the tests yet because I haven't had time due to other projects but hopefully soon I'll finish getting the tests done and can run them.

**Comment by jayden-emergence** [comment]
I think I've got all the tests needed for my code written.

Created 3 virtual environments for python 2.7, 3.4, 3.5, and 3.6 and ran the tests on the latests versions of django that you have listed under your requirements.  All tests ran successfully.

**Comment by BertrandBordage** [comment]
I gave this proposal much thinking, and I’m pretty sure it’s a bad idea to provide this kind of tool. Data can be lost with a tool like that. During the time when cachalot is completely disabled in a thread, the other threads can fetch stale data and save it back to the database, ending up losing modifications that a long-running script modified a few minutes/hours before.

There’s no going around it: if we want something safe, we cannot have a mixed situation like this. The only safe solution is to keep invalidating when data is modified, which is what django-cachalot does when `CACHALOT_ENABLED` is `False`.

You can still change the state of `CACHALOT_ENABLED`, but it’s not recommended because it’s not 100% safe either: during the time we update the settings, there’s around 1 ms during which concurrent writes fail to invalidate the cache. That method of changing the state of `CACHALOT_ENABLED` dynamically is visible in `CachalotPanel`, use:
```python
from cachalot.settings import cachalot_settings
from django.conf import settings

settings.CACHALOT_ENABLED = False
cachalot_settings.reload()
```

I chose to keep it in `CachalotPanel` because it is made to be used only in development environments, typically with just one process, no concurrency all that on a disposable non-master database.

Thank you for the solution you provide in #88, it’s very cool of you to share it, it can even be used as a workaround if others don’t agree with me. However, I’ll not merge it because, in addition to the concerns above, it feels over-engineered for such a simple feature. It doesn’t add much compare to my not-recommended-workaround above, from what I understand. Yes, it adds a context manager, but it could be easily added to the workaround above with something like:
```python
from contextlib import contextmanager

from cachalot.settings import cachalot_settings
from django.conf import settings

@contextmanager
def cachalot_disabled():
    settings.CACHALOT_ENABLED = False
    cachalot_settings.reload()
    try:
        yield
    finally:
        settings.CACHALOT_ENABLED = True
        cachalot_settings.reload()

with cachalot_disabled():
    …
```
