### ISSUE TITLE
Cachalot should raise UncachableQuery for queries with subqueries

### ISSUE THREAD

**Issue by koleror** [BertrandBordage/django-cachalot#91]
When doing a query like this:
`ModelA.objects.filter(id__in=self.modelbs.values_list("model_a", flat=True))`

The result may be wrong if the queryset is cached and the subquery's queryset changes.
In our context, we had a different result between `len(queryset)` gave another result than `queryset.count()` (which we still don't understand)
To fix it, we added this:
``` 
if "in (select" in sql.lower():
   raise UncachableQuery
```
in the `CACHALOT_QUERY_KEYGEN` function that we overrided.

Do you have a better way to handle this?

**Comment by BertrandBordage** [comment]
Is that a supposition or do you have evidence to support the claim that the result may be wrong?

I’m asking because django-cachalot correctly invalidates subqueries, as tested in detail here: https://github.com/BertrandBordage/django-cachalot/blob/809ef63fd9b75d24379b4d6b560490cc004dbbd1/cachalot/tests/write.py#L383-L585

**Comment by koleror** [comment]
I'm pretty sure there is a problem as we encountered it and we had invalid results.
We could also replay the problem to confirm it at that time.
But I can't remember exactly how to do it now.

**Comment by BertrandBordage** [comment]
OK, I’ll close it for now, but I’m still interested in an example showing a defect of this functionality :)
